max_retries = 3
max_concurrency = 20
timeout = 20
retry_wait_time = 5
user_agent = "Mozilla/5.0 (compatible; lychee-link-checker/0.21; +https://github.com/lycheeverse/lychee)"
accept = [200, 403, 429]

exclude = [
  "^https://img\\.shields\\.io",
  "^https://licensebuttons\\.net",
  "^https://api\\.star-history\\.com",
  "^https://star-history\\.com",
  "^https?://dl\\.acm\\.org",
  "^https?://ieeexplore\\.ieee\\.org",
  "^https?://link\\.springer\\.com",
  "^https?://pdfs\\.semanticscholar\\.org",
  "^https?://www\\.researchgate\\.net",
  "^https?://citeseerx\\.ist\\.psu\\.edu",
  "^https?://web\\.stanford\\.edu",
  "^http://frl\\.niche\\.tohoku\\.ac\\.jp/pdf/2010-ICRA-DING-online\\.pdf$",
  "^http://image\\.diku\\.dk/kenny/download/",
  "^http://research\\.cs\\.rutgers\\.edu/~tedmunds/publications/FFD-siggraph2005\\.pdf$",
  "^http://twiki\\.cs\\.rpi\\.edu/foswiki/pub/RoboticsWeb/LabPublications/FlickingerICRA2013\\.pdf$",
  "^http://www\\.cds\\.caltech\\.edu/~murray/books/MLS/pdf/mls94-complete\\.pdf$",
  "^http://www\\.cs\\.rpi\\.edu/~trink/Papers/STijnme96\\.pdf$",
  "^http://www\\.ent\\.mrt\\.ac\\.lk/iml/paperbase/",
  "^http://www\\.ltd\\.techfak\\.fau\\.de/Team/Leyendecker/",
  "^http://www\\.ltd\\.tf\\.fau\\.de/Team/Leyendecker/",
  "^https://wwwx\\.cs\\.unc\\.edu/~geom/papers/documents/articles/2017/LiSheng_IROS_2017\\.pdf$",
]
